import { createElement, useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { ReactElement } from "react";
import packageJson from "../package.json" with { type: "json" };
import type {
  OAuthClientProvider,
  OAuthDiscoveryState,
} from "@modelcontextprotocol/sdk/client/auth.js";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StreamableHTTPClientTransport } from "@modelcontextprotocol/sdk/client/streamableHttp.js";
import type {
  OAuthClientInformationMixed,
  OAuthClientMetadata,
  OAuthTokens,
  AuthorizationServerMetadata,
  OAuthProtectedResourceMetadata,
} from "@modelcontextprotocol/sdk/shared/auth.js";
import type { FetchLike } from "@modelcontextprotocol/sdk/shared/transport.js";
import type {
  Implementation,
  InitializeResult,
  Prompt,
  Resource,
  ResourceTemplate,
  ServerCapabilities,
  Tool,
} from "@modelcontextprotocol/sdk/types.js";

export const MCP_OAUTH_CALLBACK_CHANNEL = "use-mcp-react:oauth-callback";

export type McpOAuthCallbackMessage = {
  code?: string;
  error?: string;
  errorDescription?: string;
  state?: string;
  type: "use-mcp-react:oauth-callback";
};

export type McpOAuthCallbackResult = {
  closeWindow: boolean;
  message: McpOAuthCallbackMessage;
};

/**
 * Public connection state for one MCP server.
 *
 * The states are intentionally about what a browser application can do next, not
 * SDK implementation phases. That keeps UI code from depending on SDK errors or
 * transport internals while still exposing enough detail for runtime setup flows.
 *
 * @see https://modelcontextprotocol.io/specification/2025-11-25/basic/authorization
 */
export type UseMcpStatus =
  | "idle"
  | "connecting"
  | "pending_auth"
  | "authenticating"
  | "loading"
  | "ready"
  | "reconnecting"
  | "failed";

/**
 * OAuth authorization is required before the MCP connection can be established.
 *
 * The hook prepares this from the SDK-generated authorization request so apps can
 * render a consent button without reconstructing OAuth parameters themselves. MCP
 * authorization uses Protected Resource Metadata for discovery, Authorization
 * Server Metadata for endpoints/capabilities, PKCE for browser public clients,
 * and Resource Indicators so issued tokens are bound to the target MCP server.
 *
 * @see https://modelcontextprotocol.io/specification/2025-11-25/basic/authorization
 * @see https://datatracker.ietf.org/doc/html/rfc9728
 * @see https://datatracker.ietf.org/doc/html/rfc8414
 * @see https://datatracker.ietf.org/doc/html/rfc7636
 * @see https://datatracker.ietf.org/doc/html/rfc8707
 */
export type McpOAuthRequirement = {
  /**
   * Fully prepared authorization request generated by the MCP SDK.
   *
   * Apps should pass this through `authorize()` from a user gesture instead of
   * opening it automatically; browsers may block popups that are not directly
   * user initiated.
   */
  authorizationUrl: URL;
  /**
   * Authorization server issuer, when discovery returned one.
   */
  issuer?: string;
  /**
   * Scopes requested for the current MCP server challenge.
   *
   * MCP treats challenge scopes as authoritative for the failed request so the
   * client does not over-request broader access than the server asked for.
   */
  scopes?: string[];
  /**
   * Whether URL-based Client ID Metadata Documents are advertised by the
   * authorization server.
   *
   * This is surfaced because browser clients often have no prior relationship
   * with arbitrary MCP servers. CIMD avoids dynamic registration when both sides
   * support it.
   *
   * @see https://datatracker.ietf.org/doc/html/draft-ietf-oauth-client-id-metadata-document-00
   */
  supportsClientMetadataDocument: boolean;
  /**
   * Whether Dynamic Client Registration is available as a fallback.
   *
   * DCR lets a browser client obtain a public client id at runtime when there is
   * no pre-registered client and CIMD is not available.
   *
   * @see https://datatracker.ietf.org/doc/html/rfc7591
   */
  supportsDynamicClientRegistration: boolean;
  type: "oauth";
};

/**
 * Bearer/API-key style auth is required, but the server did not advertise MCP
 * OAuth metadata.
 *
 * In this case the app should collect or provide a bearer token itself. The hook
 * does not persist these tokens because API-key storage policy is application
 * specific.
 *
 * @see https://datatracker.ietf.org/doc/html/rfc6750
 * @see https://datatracker.ietf.org/doc/html/rfc9728
 */
export type McpBearerAuthRequirement = {
  reason: "oauth_metadata_absent";
  realm?: string;
  scopes?: string[];
  type: "bearer";
};

/**
 * OAuth metadata was discovered, but the authorization server cannot produce a
 * browser public client automatically.
 *
 * Apps should collect a pre-registered public `clientId` and reconnect with
 * `oauth.clientId`. The hook still handles PKCE, state validation, token
 * exchange, and MCP connection lifecycle after the client id is supplied.
 */
export type McpManualOAuthClientRequirement = {
  authorizationEndpoint?: string;
  issuer?: string;
  reason: "client_registration_unavailable";
  suggestedFields: ["clientId"];
  supportsClientMetadataDocument: false;
  supportsDynamicClientRegistration: false;
  tokenEndpoint?: string;
  type: "manual_oauth_client";
};

/**
 * Normalized auth diagnosis for one MCP server.
 *
 * This is the public alternative to making app code inspect SDK exception text
 * or raw `WWW-Authenticate` headers.
 */
export type McpAuthRequirement =
  | McpBearerAuthRequirement
  | McpManualOAuthClientRequirement
  | McpOAuthRequirement;

/**
 * OAuth client configuration for MCP servers that cannot rely on default DCR.
 *
 * Leave this empty for the normal remote-MCP path: the SDK will use MCP
 * authorization discovery and Dynamic Client Registration when the server
 * advertises it. Provide `clientId` for authorization servers, such as many
 * Google/Gmail deployments, that require a client to be registered out of band.
 * Provide `clientMetadataUrl` for servers that support Client ID Metadata
 * Documents and can use an HTTPS metadata document URL as the public client id.
 *
 * @see https://modelcontextprotocol.io/specification/2025-11-25/basic/authorization
 * @see https://datatracker.ietf.org/doc/html/draft-ietf-oauth-client-id-metadata-document-00
 * @see https://datatracker.ietf.org/doc/html/rfc7591
 */
export type UseMcpOAuthOptions = {
  /**
   * Pre-registered public OAuth client id.
   *
   * Use this when the authorization server does not expose Dynamic Client
   * Registration and cannot accept a Client ID Metadata Document URL. The hook
   * still uses PKCE and the SDK token exchange path; only client registration is
   * supplied by the host app.
   */
  clientId?: string;
  /**
   * OAuth client metadata sent during DCR or published by a CIMD document.
   *
   * The hook provides browser-safe defaults for a public PKCE client. Override
   * this when an MCP server requires a narrower scope, specific display name, or
   * metadata that matches a published Client ID Metadata Document.
   */
  clientMetadata?: OAuthClientMetadata;
  /**
   * HTTPS URL for a Client ID Metadata Document.
   *
   * The MCP SDK will use this as the client id only when the authorization
   * server advertises URL-based client identifiers. The URL must be HTTPS and
   * non-root because the authorization server fetches it independently.
   */
  clientMetadataUrl?: string;
  /**
   * OAuth callback URL registered with the authorization server.
   *
   * Defaults to `/oauth/callback` on the current browser origin. Manual client
   * registration must use the exact same redirect URI.
   */
  redirectUrl?: URL | string;
};

export type UseMcpTransportProxy = URL | string;

export type McpStorage = {
  getItem(key: string): Promise<string | null>;
  removeItem(key: string): Promise<void>;
  setItem(key: string, value: string): Promise<void>;
};

/**
 * Configuration for one `useMcp` hook instance.
 *
 * Keep one hook instance scoped to one MCP server URL. OAuth client information,
 * PKCE verifier state, bearer credentials, refresh tokens, server capabilities,
 * and catalog results all belong to that server boundary.
 *
 * @see https://modelcontextprotocol.io/specification/2025-11-25/basic/authorization
 */
export type UseMcpOptions = {
  /**
   * App-owned bearer token for API-key style MCP servers.
   *
   * Passing this skips OAuth discovery and sends `Authorization: Bearer ...`
   * immediately. The hook deliberately does not store this value because API key
   * persistence, rotation, masking, and revocation are product policy decisions.
   *
   * @see https://datatracker.ietf.org/doc/html/rfc6750
   */
  bearerToken?: string;
  /**
   * Gates browser side effects.
   *
   * Auto-connect is on by default when `url` is non-empty and parseable. Set this
   * to `false` when the URL is still being edited, when a form has not been
   * submitted, or when another UI state should pause network work.
   */
  enabled?: boolean;
  /**
   * OAuth client configuration for manual registration and CIMD flows.
   *
   * Most MCP servers should work without this field. Configure it only when the
   * authorization server requires an existing client id or advertises Client ID
   * Metadata Documents.
   */
  oauth?: UseMcpOAuthOptions;
  /**
   * Hook-owned OAuth storage.
   *
   * Defaults to server-scoped `localStorage` in the browser. Pass `false` to keep
   * OAuth client information, tokens, discovery, and PKCE state in memory only.
   * Bearer tokens are always app-owned and are never persisted by the hook.
   */
  storage?: McpStorage | false;
  /**
   * Same-origin proxy for MCP transport requests.
   *
   * Keep `url` pointed at the upstream MCP server so OAuth Resource Indicator
   * validation remains bound to the real protected resource. When this is set,
   * only requests to that exact MCP endpoint are sent to the proxy with
   * `x-mcp-target-url` identifying the upstream target. OAuth discovery,
   * registration, token exchange, and refresh requests remain browser-owned and
   * direct.
   */
  transportProxy?: UseMcpTransportProxy;
  /**
   * Streamable HTTP MCP endpoint.
   *
   * `null`, `undefined`, an empty string, or an unparseable URL keep the hook in
   * `idle` so apps can bind this directly to runtime URL input without causing
   * accidental requests while the user types.
   */
  url?: URL | string | null;
};

export type AuthorizationTarget = Window;

/**
 * One-shot overrides for `connect`, `reconnect`, and `reauthorize` actions.
 *
 * These options are merged with the hook's current options for a single action
 * call. Use them for user-entered credentials, a pre-opened OAuth popup, or a
 * stronger OAuth reset than the default reconnect behavior.
 */
export type UseMcpActionOptions = Partial<UseMcpOptions> & {
  /**
   * Browser window to navigate after OAuth discovery prepares an authorization
   * URL, or `"popup"` for a hook-owned popup opened during the user gesture.
   */
  authorizationTarget?: AuthorizationTarget | "popup";
  /**
   * Clears stored OAuth client registration during `reauthorize`.
   *
   * Most apps should leave this false so Dynamic Client Registration results can
   * be reused across authorization attempts.
   */
  clearClient?: boolean;
  /**
   * Clears cached OAuth discovery metadata during `reauthorize`.
   *
   * Use this after server auth configuration changes or when debugging stale
   * metadata.
   */
  clearDiscovery?: boolean;
};

/**
 * Result returned by async hook actions.
 *
 * Action failures are intentionally structured so UI code can branch without
 * parsing exception text.
 */
export type McpActionResult =
  | { ok: true }
  /** A requested hook-owned popup could not be opened by the browser. */
  | { ok: false; reason: "popup_blocked" }
  /** `authorize` or `finishAuthorization` ran before an OAuth attempt existed. */
  | { ok: false; reason: "no_pending_authorization" }
  /** The OAuth callback did not include a `state` parameter. */
  | { ok: false; reason: "missing_oauth_state" }
  /** The OAuth callback state did not match the pending authorization attempt. */
  | { ok: false; reason: "oauth_state_mismatch" }
  /** The current pending auth requirement is not an OAuth authorization flow. */
  | { ok: false; reason: "not_oauth" }
  /** The action failed with an exception that callers may log or display. */
  | { ok: false; reason: "failed"; error: Error };

/**
 * Result returned by `useMcp`.
 *
 * The raw SDK `client` and `transport` are exposed for advanced callers, while
 * the hook owns their lifecycle. Catalog arrays are always arrays so consumers
 * can render directly without null checks; unsupported MCP catalog capabilities
 * resolve to empty arrays.
 */
export type UseMcpResult = {
  /**
   * Current normalized auth requirement, or `null` while idle/connecting/error.
   */
  authRequirement: McpAuthRequirement | null;
  authDiagnostics: McpAuthDiagnostics | null;
  /**
   * Prepared OAuth authorization URL, when OAuth is pending.
   *
   * This URL comes from the SDK auth flow after discovery, client registration,
   * PKCE verifier creation, and resource binding. Use `authorize()` to open it
   * from a user gesture.
   */
  authorizationUrl: URL | null;
  /**
   * Opens or focuses the pending OAuth popup.
   *
   * Browsers generally require popup creation to happen inside a user gesture, so
   * the hook prepares `authorizationUrl` during probing but leaves the visible
   * navigation to this explicit action.
   */
  authorize: (options?: { target?: AuthorizationTarget | "popup" }) => Promise<McpActionResult>;
  catalogErrors: CatalogErrors;
  catalogStatus: CatalogStatus;
  /**
   * Connected SDK client, or `null` until initialization and catalog loading are
   * complete.
   */
  client: Client | null;
  /**
   * Starts or retries a connection using the current options.
   */
  connect: (options?: UseMcpActionOptions) => Promise<McpActionResult>;
  /**
   * Closes the active SDK client/transport without clearing loaded server
   * metadata or catalog arrays.
   */
  disconnect: () => Promise<McpActionResult>;
  /**
   * Last unrecoverable connection/auth/catalog error.
   */
  error: Error | null;
  /**
   * Completes the OAuth authorization-code callback.
   *
   * The code is exchanged through the SDK transport so PKCE, token endpoint
   * authentication, and Resource Indicators stay on the standards path.
   *
   * @see https://datatracker.ietf.org/doc/html/rfc7636
   * @see https://datatracker.ietf.org/doc/html/rfc8707
   */
  finishAuthorization: (code: string, state: string) => Promise<McpActionResult>;
  /**
   * Clears stored hook-owned auth state for this server.
   *
   * This closes any current connection, drops in-memory OAuth client
   * registration/tokens and pending authorization state, and returns the hook to
   * `idle`.
   */
  forget: () => Promise<McpActionResult>;
  /**
   * Prompt catalog returned by `prompts/list`, or an empty array when unsupported
   * or not connected.
   */
  prompts: Prompt[];
  /**
   * Starts a fresh OAuth authorization attempt for this server.
   *
   * This clears OAuth tokens and PKCE verifier state so the next attempt asks the
   * authorization server for a fresh grant. Dynamic client registration and
   * discovery are reused unless `clearClient` or `clearDiscovery` is provided.
   */
  reauthorize: (options?: UseMcpActionOptions) => Promise<McpActionResult>;
  /**
   * Closes the current connection and connects again, optionally with one-off
   * option overrides such as a newly entered bearer token.
   *
   * Reconnect preserves reusable hook-owned OAuth state so transient transport
   * failures do not force a new consent flow.
   */
  reconnect: (options?: UseMcpActionOptions) => Promise<McpActionResult>;
  /**
   * Resource template catalog returned by `resources/templates/list`, or an empty
   * array when unsupported or not connected.
   */
  resourceTemplates: ResourceTemplate[];
  /**
   * Resource catalog returned by `resources/list`, or an empty array when
   * unsupported or not connected.
   */
  resources: Resource[];
  /**
   * Server capabilities reported by MCP initialize.
   */
  serverCapabilities: ServerCapabilities | null;
  /**
   * Server implementation metadata reported by MCP initialize.
   */
  serverVersion: Implementation | null;
  /**
   * Runtime-derived description of the MCP endpoint discovered through
   * initialization, safe transport state, auth classification, and catalog list
   * calls.
   */
  serverProfile: McpServerProfile | null;
  /**
   * Current connection state for UI branching.
   */
  status: UseMcpStatus;
  /**
   * Tool catalog returned by `tools/list`, or an empty array when unsupported or
   * not connected.
   */
  tools: Tool[];
  /**
   * Connected Streamable HTTP transport, or `null` until initialization and
   * catalog loading are complete.
   */
  transport: StreamableHTTPClientTransport | null;
};

/**
 * Status of the initial MCP catalog load after initialize.
 *
 * Catalog failures do not necessarily close the MCP connection. A server can be
 * `ready` while one catalog section is `partial` or `error`.
 */
export type CatalogStatus = "idle" | "loading" | "ready" | "partial" | "error";

/**
 * Per-section catalog errors captured when the MCP connection remains usable.
 */
export type CatalogErrors = {
  prompts?: unknown;
  resourceTemplates?: unknown;
  resources?: unknown;
  tools?: unknown;
};

/**
 * Diagnostic snapshot of the initialized MCP server.
 *
 * Prefer the top-level hook state for app control flow. Use this profile for
 * setup guidance, debug panes, and proof-of-life displays.
 */
export type McpServerProfile = {
  auth: McpAuthProfile;
  catalog: McpCatalogSnapshot;
  fetchedAt: number;
  initialize: InitializeResult | null;
  transport: McpTransportProfile;
  url: string;
};

/**
 * Transport metadata observed from the Streamable HTTP MCP connection.
 */
export type McpTransportProfile = {
  endpoint: string;
  kind: "streamable-http";
  protocolVersion?: string;
  sessionMode: "stateful" | "stateless" | "unknown";
};

/**
 * Public auth classification for the initialized MCP server.
 *
 * This exposes stable diagnostics without requiring consumers to inspect SDK
 * discovery internals.
 */
export type McpAuthProfile =
  | { mode: "none" }
  | {
      mode: "oauth-protected";
      authorizationServerMetadata?: AuthorizationServerMetadata;
      authorizationServerUrl?: string;
      protectedResourceMetadata?: OAuthProtectedResourceMetadata;
      protectedResourceMetadataUrl?: string;
    }
  | {
      mode: "external-bearer";
      realm?: string;
      scopes?: string[];
    }
  | {
      mode: "unknown";
      reason?: string;
    };

/**
 * Snapshot of all catalog sections loaded during initial connection.
 */
export type McpCatalogSnapshot = {
  prompts: McpCatalogSection<Prompt>;
  resourceTemplates: McpCatalogSection<ResourceTemplate>;
  resources: McpCatalogSection<Resource>;
  tools: McpCatalogSection<Tool>;
};

/**
 * One MCP catalog section and its pagination/error state.
 */
export type McpCatalogSection<Item> = {
  complete: boolean;
  error?: unknown;
  items: Item[];
  nextCursor?: string;
};

/**
 * Stable auth diagnostics for debug UI and playgrounds.
 */
export type McpAuthDiagnostics = {
  authorizationServerMetadataUrl?: string;
  issuer?: string;
  lastError?: Error;
  registrationStrategy?: "client_id" | "client_metadata_url" | "dynamic_client_registration";
  resourceMetadataUrl?: string;
  scopes?: string[];
};

const EMPTY_TOOLS: Tool[] = [];
const EMPTY_RESOURCES: Resource[] = [];
const EMPTY_RESOURCE_TEMPLATES: ResourceTemplate[] = [];
const EMPTY_PROMPTS: Prompt[] = [];
const MAX_CATALOG_PAGES = 25;
const RECONNECT_STATUS_PAINT_DELAY_MS = 80;
const AUTHENTICATING_STATUS_PAINT_DELAY_MS = 80;
const MCP_CLIENT_VERSION = packageJson.version;

type Connection = {
  client: Client;
  transport: StreamableHTTPClientTransport;
};

type PendingOAuthConnection = {
  connection: Connection;
  options: UseMcpActionOptions;
  provider: PendingOAuthProvider;
};

type PreparedAuthorizationTargetResult =
  | { ok: true; ownsTarget?: boolean; target?: AuthorizationTarget }
  | Extract<McpActionResult, { ok: false }>;

type UseMcpState = {
  authRequirement: McpAuthRequirement | null;
  authDiagnostics: McpAuthDiagnostics | null;
  authorizationUrl: URL | null;
  catalogErrors: CatalogErrors;
  catalogStatus: CatalogStatus;
  client: Client | null;
  error: Error | null;
  prompts: Prompt[];
  resourceTemplates: ResourceTemplate[];
  resources: Resource[];
  serverCapabilities: ServerCapabilities | null;
  serverProfile: McpServerProfile | null;
  serverVersion: Implementation | null;
  status: UseMcpStatus;
  tools: Tool[];
  transport: StreamableHTTPClientTransport | null;
};

const IDLE_STATE: UseMcpState = {
  authRequirement: null,
  authDiagnostics: null,
  authorizationUrl: null,
  catalogErrors: {},
  catalogStatus: "idle",
  client: null,
  error: null,
  prompts: EMPTY_PROMPTS,
  resourceTemplates: EMPTY_RESOURCE_TEMPLATES,
  resources: EMPTY_RESOURCES,
  serverCapabilities: null,
  serverProfile: null,
  serverVersion: null,
  status: "idle",
  tools: EMPTY_TOOLS,
  transport: null,
};

/**
 * Reads the current OAuth callback URL and delivers it to waiting hook
 * instances.
 *
 * `targetOrigin` is used only for `window.opener.postMessage`. The
 * `BroadcastChannel` delivery remains same-origin browser messaging and helps
 * when providers or browsers make `window.opener` unavailable.
 */
export function handleMcpOAuthCallback(
  options: {
    closeWindow?: boolean;
    targetOrigin?: string;
  } = {},
): McpOAuthCallbackResult {
  const result = readMcpOAuthCallbackResult(options);
  const targetOrigin = options.targetOrigin ?? window.location.origin;

  window.opener?.postMessage(result.message, targetOrigin);

  const channel = new BroadcastChannel(MCP_OAUTH_CALLBACK_CHANNEL);
  channel.postMessage(result.message);
  channel.close();

  if (result.closeWindow) {
    window.close();
  }

  return result;
}

function readMcpOAuthCallbackResult(
  options: {
    closeWindow?: boolean;
  } = {},
): McpOAuthCallbackResult {
  const params = new URLSearchParams(window.location.search);
  const message: McpOAuthCallbackMessage = {
    ...(params.get("code") ? { code: params.get("code")! } : {}),
    ...(params.get("error") ? { error: params.get("error")! } : {}),
    ...(params.get("error_description")
      ? { errorDescription: params.get("error_description")! }
      : {}),
    ...(params.get("state") ? { state: params.get("state")! } : {}),
    type: "use-mcp-react:oauth-callback",
  };
  const shouldClose = options.closeWindow !== false && !message.error;

  return {
    closeWindow: shouldClose,
    message,
  };
}

/**
 * Minimal React callback page for the default `/oauth/callback` route.
 *
 * Mount this component at the redirect URL configured with the authorization
 * server. It posts the callback result to the opener and through
 * `BroadcastChannel`, then renders a fallback page for browsers that cannot
 * close the popup automatically.
 */
export function McpOAuthCallback(): ReactElement {
  const [result, setResult] = useState(() => readMcpOAuthCallbackResult());
  const handledCallbackRef = useRef(false);

  useEffect(() => {
    if (handledCallbackRef.current) {
      return;
    }

    handledCallbackRef.current = true;
    setResult(handleMcpOAuthCallback());
  }, []);

  return createElement(
    "main",
    {
      style: {
        color: "#18231f",
        fontFamily:
          'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
        padding: "32px",
      },
    },
    createElement(
      "h1",
      null,
      result.message.error ? "Authorization failed" : "Authorization complete",
    ),
    createElement(
      "p",
      null,
      result.message.error
        ? (result.message.errorDescription ?? result.message.error)
        : result.closeWindow
          ? "This window can be closed."
          : "Return to the application to continue.",
    ),
  );
}

/**
 * Connects a React component to one Streamable HTTP MCP server.
 *
 * The hook probes the server when `url` is present and `enabled !== false`,
 * then classifies the next browser-visible action: no auth, OAuth consent,
 * bearer token entry, ready, or failure. It intentionally uses the real MCP
 * SDK client and Streamable HTTP transport so initialization, catalog calls,
 * OAuth discovery, PKCE, Dynamic Client Registration, token refresh, and
 * Resource Indicators stay on the protocol path.
 *
 * Use one hook instance per MCP server. That keeps auth state, token audience,
 * server capabilities, and catalogs scoped to the resource server that issued
 * them.
 *
 * @see https://modelcontextprotocol.io/specification/2025-11-25/basic/authorization
 * @see https://modelcontextprotocol.io/specification/2025-11-25/basic/transports
 * @see https://datatracker.ietf.org/doc/html/rfc9728
 * @see https://datatracker.ietf.org/doc/html/rfc8707
 */
export function useMcp(options: UseMcpOptions): UseMcpResult {
  const [state, setState] = useState<UseMcpState>(IDLE_STATE);
  const connectionRef = useRef<Connection | null>(null);
  const connectionGenerationRef = useRef(0);
  const optionsRef = useRef(options);
  const oauthProviderKeyRef = useRef<string | null>(null);
  const oauthProviderRef = useRef<PendingOAuthProvider | null>(null);
  const pendingOAuthConnectionRef = useRef<PendingOAuthConnection | null>(null);
  const pendingOAuthFinishPromiseRef = useRef<Promise<McpActionResult> | null>(null);
  const popupRef = useRef<Window | null>(null);
  const popupOwnedByHookRef = useRef(false);
  const popupWindowNameRef = useRef<string | null>(null);
  const stateRef = useRef(state);

  optionsRef.current = options;
  stateRef.current = state;

  const closeCurrentConnections = useCallback(async () => {
    const connection = connectionRef.current;
    const pendingOAuthConnection = pendingOAuthConnectionRef.current?.connection;
    connectionRef.current = null;
    pendingOAuthConnectionRef.current = null;
    pendingOAuthFinishPromiseRef.current = null;

    if (connection) {
      await closeConnection(connection);
    }
    if (pendingOAuthConnection && pendingOAuthConnection !== connection) {
      await closeConnection(pendingOAuthConnection);
    }
  }, []);

  const closeHookOwnedPopup = useCallback(() => {
    const popup = popupRef.current;
    if (
      popup &&
      popupOwnedByHookRef.current &&
      !popup.closed &&
      typeof popup.close === "function"
    ) {
      popup.close();
    }
    popupRef.current = null;
    popupOwnedByHookRef.current = false;
    popupWindowNameRef.current = null;
  }, []);

  const oauthPopupWindowName = useCallback(() => {
    popupWindowNameRef.current ??= createOAuthPopupWindowName();

    return popupWindowNameRef.current;
  }, []);

  const connectWithOptions = useCallback(
    async (
      connectionOptions: UseMcpActionOptions,
      existingOAuthProvider?: PendingOAuthProvider,
      lifecycle: "connect" | "reconnect" = "connect",
    ): Promise<McpActionResult> => {
      const url = normalizeMcpUrl(connectionOptions.url);
      const generation = connectionGenerationRef.current + 1;
      connectionGenerationRef.current = generation;

      if (connectionOptions.enabled === false || !url) {
        await closeCurrentConnections();
        closeHookOwnedPopup();
        if (connectionGenerationRef.current !== generation) {
          return { ok: true };
        }
        setState(IDLE_STATE);
        return { ok: true };
      }

      closeHookOwnedPopup();

      let lastAuthenticateHeader: string | null = null;
      const client = new Client({ name: "use-mcp-react", version: MCP_CLIENT_VERSION });
      const oauthProviderKey = createOAuthProviderKey(url, connectionOptions);
      const oauthProvider = connectionOptions.bearerToken
        ? undefined
        : (existingOAuthProvider ??
          (oauthProviderRef.current && oauthProviderKeyRef.current === oauthProviderKey
            ? oauthProviderRef.current
            : new PendingOAuthProvider(
                url,
                connectionOptions.oauth,
                resolveMcpStorage(connectionOptions.storage),
              )));
      if (!existingOAuthProvider) {
        oauthProvider?.clearAuthenticationChallenge();
      }
      const authorizationTargetResult = prepareAuthorizationTarget(
        oauthProvider,
        connectionOptions.authorizationTarget,
        oauthPopupWindowName,
      );
      if (!authorizationTargetResult.ok) {
        return authorizationTargetResult;
      }
      if (authorizationTargetResult.target) {
        popupRef.current = authorizationTargetResult.target;
        popupOwnedByHookRef.current = authorizationTargetResult.ownsTarget === true;
      }
      oauthProviderRef.current = oauthProvider ?? null;
      oauthProviderKeyRef.current = oauthProvider ? oauthProviderKey : null;
      const authProvider = connectionOptions.bearerToken
        ? createStaticBearerAuthProvider(connectionOptions.bearerToken)
        : oauthProvider;
      const transport = new StreamableHTTPClientTransport(url, {
        ...(authProvider ? { authProvider } : {}),
        fetch: createAuthenticationChallengeCapturingFetch({
          oauthProvider,
          onAuthenticateHeader: (header) => {
            lastAuthenticateHeader = header;
            oauthProvider?.captureAuthenticationChallenge(header);
          },
          serverUrl: url,
          transportProxy: connectionOptions.transportProxy,
        }),
      });
      const connection = { client, transport };
      await closeCurrentConnections();
      if (connectionGenerationRef.current !== generation) {
        await closeConnection(connection);
        return { ok: true };
      }
      connectionRef.current = connection;
      const preserveCatalog = lifecycle === "reconnect";

      setState((current) => ({
        ...(preserveCatalog ? current : IDLE_STATE),
        authRequirement: null,
        authDiagnostics: null,
        authorizationUrl: null,
        client: null,
        error: null,
        status: preserveCatalog ? "reconnecting" : "connecting",
        transport: null,
      }));
      if (preserveCatalog) {
        await yieldToBrowser(RECONNECT_STATUS_PAINT_DELAY_MS);
        if (connectionGenerationRef.current !== generation) {
          if (connectionRef.current === connection) {
            connectionRef.current = null;
          }
          await closeConnection(connection);
          return { ok: true };
        }
      }

      try {
        await client.connect(transport);
        if (connectionGenerationRef.current !== generation) {
          if (connectionRef.current === connection) {
            connectionRef.current = null;
          }
          await closeConnection(connection);
          return { ok: true };
        }
        const serverCapabilities = client.getServerCapabilities() ?? null;
        const serverVersion = client.getServerVersion() ?? null;
        const initialize = createInitializeResult(client, transport, {
          serverCapabilities,
          serverVersion,
        });
        setState((current) => ({
          ...current,
          authRequirement: null,
          authDiagnostics: null,
          authorizationUrl: null,
          catalogErrors: {},
          catalogStatus: "loading",
          client: null,
          error: null,
          serverCapabilities,
          serverProfile: null,
          serverVersion,
          status: "loading",
          transport: null,
        }));
        const catalog = await loadCatalog(client, serverCapabilities);

        if (connectionGenerationRef.current !== generation) {
          await closeConnection(connection);
          return { ok: true };
        }

        closeHookOwnedPopup();
        setState({
          authRequirement: null,
          authDiagnostics: null,
          authorizationUrl: null,
          catalogErrors: catalog.errors,
          catalogStatus: catalog.status,
          client,
          error: null,
          prompts: catalog.prompts,
          resourceTemplates: catalog.resourceTemplates,
          resources: catalog.resources,
          serverCapabilities,
          serverProfile: createServerProfile({
            auth: createAuthProfile(connectionOptions, oauthProvider),
            catalog,
            initialize,
            transport,
            url,
          }),
          serverVersion,
          status: "ready",
          tools: catalog.tools,
          transport,
        });
        pendingOAuthConnectionRef.current = null;
        return { ok: true };
      } catch (cause) {
        if (connectionGenerationRef.current !== generation) {
          await closeConnection(connection);
          return { ok: true };
        }

        const bearerRequirement = parseBearerAuthRequirement(lastAuthenticateHeader);
        if (bearerRequirement) {
          await closeConnection(connection);
          closeHookOwnedPopup();
          if (connectionGenerationRef.current !== generation) {
            return { ok: true };
          }
          setState((current) => ({
            ...(preserveCatalog ? current : IDLE_STATE),
            authRequirement: bearerRequirement,
            authDiagnostics: null,
            authorizationUrl: null,
            client: null,
            error: null,
            status: "pending_auth",
            transport: null,
          }));
          return { ok: true };
        }

        const oauthRequirement = oauthProvider?.authRequirement();
        const oauthTokens = oauthProvider ? await oauthProvider.tokens() : undefined;
        if (oauthRequirement && oauthProvider && !oauthTokens) {
          pendingOAuthConnectionRef.current = {
            connection,
            options: connectionOptions,
            provider: oauthProvider,
          };
          setState((current) => ({
            ...(preserveCatalog ? current : IDLE_STATE),
            authRequirement: oauthRequirement,
            authDiagnostics: oauthProvider.authDiagnostics(),
            authorizationUrl: oauthRequirement.authorizationUrl,
            client: null,
            error: null,
            status: "pending_auth",
            transport: null,
          }));
          return { ok: true };
        }

        const manualOAuthInference = await inferManualOAuthClientRequirement(
          url,
          lastAuthenticateHeader,
        );
        if (connectionGenerationRef.current !== generation) {
          await closeConnection(connection);
          return { ok: true };
        }
        if (manualOAuthInference) {
          await closeConnection(connection);
          closeHookOwnedPopup();
          if (connectionGenerationRef.current !== generation) {
            return { ok: true };
          }
          setState((current) => ({
            ...(preserveCatalog ? current : IDLE_STATE),
            authRequirement: manualOAuthInference.requirement,
            authDiagnostics: {
              authorizationServerMetadataUrl: manualOAuthInference.authorizationServerMetadataUrl,
              issuer: manualOAuthInference.requirement.issuer,
              resourceMetadataUrl: manualOAuthInference.resourceMetadataUrl,
            },
            authorizationUrl: null,
            client: null,
            error: null,
            status: "pending_auth",
            transport: null,
          }));
          return { ok: true };
        }

        await closeConnection(connection);
        closeHookOwnedPopup();
        if (connectionGenerationRef.current !== generation) {
          return { ok: true };
        }
        setState((current) => ({
          ...(preserveCatalog ? current : IDLE_STATE),
          authRequirement: null,
          authDiagnostics: null,
          authorizationUrl: null,
          client: null,
          error: cause instanceof Error ? cause : new Error(String(cause)),
          status: "failed",
          transport: null,
        }));
        return {
          ok: false,
          reason: "failed",
          error: cause instanceof Error ? cause : new Error(String(cause)),
        };
      }
    },
    [closeCurrentConnections, closeHookOwnedPopup, oauthPopupWindowName],
  );

  const connect = useCallback(
    async (overrideOptions?: UseMcpActionOptions) => {
      return connectWithOptions(mergeUseMcpActionOptions(optionsRef.current, overrideOptions));
    },
    [connectWithOptions],
  );
  const disconnect = useCallback(async (): Promise<McpActionResult> => {
    const generation = connectionGenerationRef.current + 1;
    connectionGenerationRef.current = generation;
    const connection = connectionRef.current;
    connectionRef.current = null;

    if (connection) {
      await closeConnection(connection);
    }
    if (connectionGenerationRef.current !== generation) {
      return { ok: true };
    }
    pendingOAuthConnectionRef.current = null;
    pendingOAuthFinishPromiseRef.current = null;
    closeHookOwnedPopup();

    setState((current) => ({
      ...current,
      authRequirement: null,
      authDiagnostics: null,
      authorizationUrl: null,
      client: null,
      error: null,
      status: "idle",
      transport: null,
    }));
    return { ok: true };
  }, [closeHookOwnedPopup]);
  const reconnect = useCallback(
    async (overrideOptions?: UseMcpActionOptions): Promise<McpActionResult> => {
      const generation = connectionGenerationRef.current + 1;
      connectionGenerationRef.current = generation;
      const connection = connectionRef.current;
      connectionRef.current = null;
      pendingOAuthConnectionRef.current = null;
      pendingOAuthFinishPromiseRef.current = null;
      closeHookOwnedPopup();

      if (connection) {
        await closeConnection(connection);
      }
      if (connectionGenerationRef.current !== generation) {
        return { ok: true };
      }

      return connectWithOptions(
        mergeUseMcpActionOptions(optionsRef.current, overrideOptions),
        undefined,
        "reconnect",
      );
    },
    [closeHookOwnedPopup, connectWithOptions],
  );
  const reauthorize = useCallback(
    async (overrideOptions?: UseMcpActionOptions): Promise<McpActionResult> => {
      const generation = connectionGenerationRef.current + 1;
      connectionGenerationRef.current = generation;
      const connection = connectionRef.current;
      const pendingOAuthConnection = pendingOAuthConnectionRef.current?.connection;
      connectionRef.current = null;
      pendingOAuthConnectionRef.current = null;
      pendingOAuthFinishPromiseRef.current = null;
      closeHookOwnedPopup();

      const provider = oauthProviderRef.current;
      if (provider) {
        await provider.invalidateCredentials("tokens");
        await provider.invalidateCredentials("verifier");
        if (overrideOptions?.clearClient) {
          await provider.invalidateCredentials("client");
        }
        if (overrideOptions?.clearDiscovery) {
          await provider.invalidateCredentials("discovery");
        }
      }

      if (connection) {
        await closeConnection(connection);
      }
      if (pendingOAuthConnection && pendingOAuthConnection !== connection) {
        await closeConnection(pendingOAuthConnection);
      }
      if (connectionGenerationRef.current !== generation) {
        return { ok: true };
      }

      return connectWithOptions(
        mergeUseMcpActionOptions(optionsRef.current, overrideOptions),
        undefined,
        "reconnect",
      );
    },
    [closeHookOwnedPopup, connectWithOptions],
  );
  const forget = useCallback(async (): Promise<McpActionResult> => {
    const generation = connectionGenerationRef.current + 1;
    connectionGenerationRef.current = generation;
    const connection = connectionRef.current;
    const pendingOAuthConnection = pendingOAuthConnectionRef.current?.connection;
    const provider = oauthProviderRef.current;
    connectionRef.current = null;
    pendingOAuthConnectionRef.current = null;
    pendingOAuthFinishPromiseRef.current = null;
    oauthProviderKeyRef.current = null;
    oauthProviderRef.current = null;
    closeHookOwnedPopup();

    if (connection) {
      await closeConnection(connection);
    }
    if (pendingOAuthConnection && pendingOAuthConnection !== connection) {
      await closeConnection(pendingOAuthConnection);
    }
    await provider?.invalidateCredentials("all");
    if (connectionGenerationRef.current !== generation) {
      return { ok: true };
    }

    setState(IDLE_STATE);
    return { ok: true };
  }, [closeHookOwnedPopup]);
  const authorize = useCallback(
    async (options?: { target?: AuthorizationTarget | "popup" }): Promise<McpActionResult> => {
      const authorizationUrl = stateRef.current.authorizationUrl;
      if (!authorizationUrl) {
        return { ok: false, reason: "no_pending_authorization" };
      }

      const requestedTarget = options?.target;
      if (requestedTarget && requestedTarget !== "popup") {
        requestedTarget.location.href = authorizationUrl.toString();
        requestedTarget.focus();
        return { ok: true };
      }

      const popup = popupRef.current;
      if (popup && !popup.closed) {
        popup.focus();
        return { ok: true };
      }

      const openedPopup = window.open(
        authorizationUrl.toString(),
        oauthPopupWindowName(),
        "width=600,height=700,resizable=yes,scrollbars=yes,status=yes",
      );
      if (!openedPopup) {
        return { ok: false, reason: "popup_blocked" };
      }
      popupRef.current = openedPopup;
      popupOwnedByHookRef.current = true;
      openedPopup.focus();
      return { ok: true };
    },
    [oauthPopupWindowName],
  );
  const finishAuthorization = useCallback(
    async (authorizationCode: string, state: string): Promise<McpActionResult> => {
      const existingFinish = pendingOAuthFinishPromiseRef.current;
      if (existingFinish) {
        return existingFinish;
      }

      const pendingOAuthConnection = pendingOAuthConnectionRef.current;
      const generation = connectionGenerationRef.current;

      if (!pendingOAuthConnection) {
        setState({
          ...IDLE_STATE,
          error: new Error("No pending OAuth authorization."),
          status: "failed",
        });
        return { ok: false, reason: "no_pending_authorization" };
      }

      const expectedState = pendingOAuthConnection.provider.pendingState();
      if (!expectedState) {
        return { ok: false, reason: "missing_oauth_state" };
      }
      if (state !== expectedState) {
        return { ok: false, reason: "oauth_state_mismatch" };
      }

      let finishPromise!: Promise<McpActionResult>;
      finishPromise = (async (): Promise<McpActionResult> => {
        setState((current) => ({
          ...current,
          error: null,
          status: "authenticating",
        }));
        await yieldToBrowser(AUTHENTICATING_STATUS_PAINT_DELAY_MS);
        if (
          connectionGenerationRef.current !== generation ||
          pendingOAuthConnectionRef.current !== pendingOAuthConnection
        ) {
          return { ok: true };
        }

        try {
          await pendingOAuthConnection.connection.transport.finishAuth(authorizationCode);
          if (
            connectionGenerationRef.current !== generation ||
            pendingOAuthConnectionRef.current !== pendingOAuthConnection
          ) {
            return { ok: true };
          }
          if (connectionRef.current === pendingOAuthConnection.connection) {
            connectionRef.current = null;
          }
          await closeConnection(pendingOAuthConnection.connection);
          pendingOAuthConnectionRef.current = null;
          return connectWithOptions(
            { ...pendingOAuthConnection.options, authorizationTarget: undefined },
            pendingOAuthConnection.provider,
          );
        } catch (cause) {
          if (
            connectionGenerationRef.current !== generation ||
            pendingOAuthConnectionRef.current !== pendingOAuthConnection
          ) {
            return { ok: true };
          }
          pendingOAuthConnectionRef.current = null;
          if (connectionRef.current === pendingOAuthConnection.connection) {
            connectionRef.current = null;
          }
          await closeConnection(pendingOAuthConnection.connection);
          setState({
            ...IDLE_STATE,
            error: cause instanceof Error ? cause : new Error(String(cause)),
            status: "failed",
          });
          return {
            ok: false,
            reason: "failed",
            error: cause instanceof Error ? cause : new Error(String(cause)),
          };
        } finally {
          if (pendingOAuthFinishPromiseRef.current === finishPromise) {
            pendingOAuthFinishPromiseRef.current = null;
          }
        }
      })();
      pendingOAuthFinishPromiseRef.current = finishPromise;
      return finishPromise;
    },
    [connectWithOptions],
  );

  useEffect(() => {
    const finishFromMessage = (message: McpOAuthCallbackMessage) => {
      const pendingOAuthConnection = pendingOAuthConnectionRef.current;
      const expectedState = pendingOAuthConnection?.provider.pendingState();
      if (!pendingOAuthConnection || !expectedState || message.state !== expectedState) {
        return;
      }

      if (message.error) {
        pendingOAuthConnectionRef.current = null;
        pendingOAuthFinishPromiseRef.current = null;
        if (connectionRef.current === pendingOAuthConnection.connection) {
          connectionRef.current = null;
        }
        closeHookOwnedPopup();
        void (async () => {
          await pendingOAuthConnection.provider.invalidateCredentials("verifier");
          await closeConnection(pendingOAuthConnection.connection);
          setState({
            ...IDLE_STATE,
            error: new Error(message.errorDescription ?? message.error),
            status: "failed",
          });
        })();
        return;
      }

      if (!message.code) {
        return;
      }

      void finishAuthorization(message.code, message.state);
    };

    const handleWindowMessage = (event: MessageEvent<unknown>) => {
      if (event.origin !== window.location.origin || !isMcpOAuthCallbackMessage(event.data)) {
        return;
      }

      finishFromMessage(event.data);
    };
    const channel = new BroadcastChannel(MCP_OAUTH_CALLBACK_CHANNEL);
    channel.onmessage = (event) => {
      if (isMcpOAuthCallbackMessage(event.data)) {
        finishFromMessage(event.data);
      }
    };

    window.addEventListener("message", handleWindowMessage);

    return () => {
      channel.close();
      window.removeEventListener("message", handleWindowMessage);
    };
  }, [closeHookOwnedPopup, finishAuthorization]);

  const oauthClientMetadataKey = stableSerializeOAuthClientMetadata(options.oauth?.clientMetadata);
  const bearerTokenKey = options.bearerToken;
  const mcpUrlKey = stableSerializeUrlDependency(options.url);
  const redirectUrlKey = stableSerializeOAuthRedirectUrlDependency(options.oauth?.redirectUrl);
  const transportProxyKey = stableSerializeTransportProxyDependency(options.transportProxy);
  const storageKey = getMcpStorageDependencyKey(options.storage);

  useEffect(() => {
    const url = normalizeMcpUrl(options.url);
    if (options.enabled === false || !url) {
      connectionGenerationRef.current += 1;
      setState(IDLE_STATE);
      return;
    }

    void connectWithOptions(options);

    return () => {
      connectionGenerationRef.current += 1;
      const connection = connectionRef.current;
      const pendingOAuthConnection = pendingOAuthConnectionRef.current?.connection;
      connectionRef.current = null;
      pendingOAuthFinishPromiseRef.current = null;
      closeHookOwnedPopup();

      if (connection) {
        void closeConnection(connection);
      }
      if (pendingOAuthConnection && pendingOAuthConnection !== connection) {
        void closeConnection(pendingOAuthConnection);
      }
      pendingOAuthConnectionRef.current = null;
    };
  }, [
    connectWithOptions,
    bearerTokenKey,
    options.enabled,
    options.oauth?.clientId,
    oauthClientMetadataKey,
    options.oauth?.clientMetadataUrl,
    redirectUrlKey,
    storageKey,
    mcpUrlKey,
    transportProxyKey,
    closeHookOwnedPopup,
  ]);

  return useMemo(
    () => ({
      authRequirement: state.authRequirement,
      authDiagnostics: state.authDiagnostics,
      authorizationUrl: state.authorizationUrl,
      authorize,
      catalogErrors: state.catalogErrors,
      catalogStatus: state.catalogStatus,
      client: state.client,
      connect,
      disconnect,
      error: state.error,
      finishAuthorization,
      forget,
      prompts: state.prompts,
      reauthorize,
      reconnect,
      resourceTemplates: state.resourceTemplates,
      resources: state.resources,
      serverCapabilities: state.serverCapabilities,
      serverProfile: state.serverProfile,
      serverVersion: state.serverVersion,
      status: state.status,
      tools: state.tools,
      transport: state.transport,
    }),
    [authorize, connect, disconnect, finishAuthorization, forget, reauthorize, reconnect, state],
  );
}

function stableSerializeOAuthClientMetadata(
  clientMetadata: OAuthClientMetadata | undefined,
): string | undefined {
  return clientMetadata ? stableSerializeJsonValue(clientMetadata) : undefined;
}

function mergeUseMcpActionOptions(
  options: UseMcpOptions,
  overrideOptions: UseMcpActionOptions | undefined,
): UseMcpActionOptions {
  if (!overrideOptions) {
    return options;
  }

  const oauth =
    overrideOptions.oauth || options.oauth
      ? {
          ...options.oauth,
          ...overrideOptions.oauth,
        }
      : undefined;

  return {
    ...options,
    ...overrideOptions,
    ...(oauth ? { oauth } : {}),
  };
}

function stableSerializeUrlDependency(url: URL | string | null | undefined): string | null {
  return normalizeMcpUrl(url)?.toString() ?? null;
}

function stableSerializeOAuthRedirectUrlDependency(url: URL | string | undefined): string | null {
  return url ? resolveOAuthRedirectUrl(url) : null;
}

function stableSerializeTransportProxyDependency(
  transportProxy: UseMcpTransportProxy | undefined,
): string | null {
  return transportProxy ? transportProxy.toString() : null;
}

function authorizationServerMetadataUrlFor(authorizationServerUrl: URL | string): string {
  const url = new URL(authorizationServerUrl);
  let pathname = url.pathname;
  if (pathname.endsWith("/")) {
    pathname = pathname.slice(0, -1);
  }

  return new URL(
    pathname
      ? `/.well-known/oauth-authorization-server${pathname}`
      : "/.well-known/oauth-authorization-server",
    url.origin,
  ).toString();
}

function stableSerializeJsonValue(value: unknown): string {
  if (value === null || typeof value !== "object") {
    return JSON.stringify(value) ?? "null";
  }

  if (Array.isArray(value)) {
    return `[${value.map((item) => stableSerializeJsonValue(item)).join(",")}]`;
  }

  const record = value as Record<string, unknown>;
  return `{${Object.keys(record)
    .filter((key) => record[key] !== undefined)
    .sort()
    .map((key) => `${JSON.stringify(key)}:${stableSerializeJsonValue(record[key])}`)
    .join(",")}}`;
}

function normalizeMcpUrl(url: URL | string | null | undefined): URL | null {
  if (url == null) {
    return null;
  }

  const value = typeof url === "string" ? url.trim() : url.toString();
  if (!value) {
    return null;
  }

  try {
    return new URL(value);
  } catch {
    return null;
  }
}

function normalizeTransportProxyUrl(transportProxy: UseMcpTransportProxy | undefined): URL | null {
  if (!transportProxy) {
    return null;
  }

  const value =
    typeof transportProxy === "string" ? transportProxy.trim() : transportProxy.toString();
  if (!value) {
    throw new Error("transportProxy must be a non-empty URL.");
  }

  const baseUrl = typeof window === "undefined" ? "http://localhost" : window.location.origin;

  let url: URL;
  try {
    url = new URL(value, baseUrl);
  } catch {
    throw new Error(`Invalid transportProxy URL: ${value}`);
  }

  if (url.origin !== new URL(baseUrl).origin) {
    throw new Error("transportProxy must be same-origin.");
  }

  return url;
}

async function loadCatalog(
  client: Client,
  serverCapabilities: ServerCapabilities | null,
): Promise<{
  errors: CatalogErrors;
  prompts: Prompt[];
  resourceTemplates: ResourceTemplate[];
  resources: Resource[];
  status: CatalogStatus;
  tools: Tool[];
  snapshot: McpCatalogSnapshot;
}> {
  const toolsPromise: Promise<LoadedCatalogSection<Tool>> = serverCapabilities?.tools
    ? loadCatalogSection((cursor) => client.listTools(cursor ? { cursor } : undefined), "tools")
    : Promise.resolve(createLoadedCatalogSection(EMPTY_TOOLS));
  const resourcesPromise: Promise<LoadedCatalogSection<Resource>> = serverCapabilities?.resources
    ? loadCatalogSection(
        (cursor) => client.listResources(cursor ? { cursor } : undefined),
        "resources",
      )
    : Promise.resolve(createLoadedCatalogSection(EMPTY_RESOURCES));
  const resourceTemplatesPromise: Promise<LoadedCatalogSection<ResourceTemplate>> =
    serverCapabilities?.resources
      ? loadCatalogSection(
          (cursor) => client.listResourceTemplates(cursor ? { cursor } : undefined),
          "resourceTemplates",
        )
      : Promise.resolve(createLoadedCatalogSection(EMPTY_RESOURCE_TEMPLATES));
  const promptsPromise: Promise<LoadedCatalogSection<Prompt>> = serverCapabilities?.prompts
    ? loadCatalogSection((cursor) => client.listPrompts(cursor ? { cursor } : undefined), "prompts")
    : Promise.resolve(createLoadedCatalogSection(EMPTY_PROMPTS));

  const [tools, resources, resourceTemplates, prompts] = await Promise.allSettled([
    toolsPromise,
    resourcesPromise,
    resourceTemplatesPromise,
    promptsPromise,
  ]);
  const errors: CatalogErrors = {};

  if (tools.status === "rejected") {
    errors.tools = tools.reason;
  }
  if (resources.status === "rejected") {
    errors.resources = resources.reason;
  }
  if (resourceTemplates.status === "rejected") {
    errors.resourceTemplates = resourceTemplates.reason;
  }
  if (prompts.status === "rejected") {
    errors.prompts = prompts.reason;
  }

  const errorCount = Object.keys(errors).length;

  const toolsValue = tools.status === "fulfilled" ? tools.value.items : EMPTY_TOOLS;
  const resourcesValue = resources.status === "fulfilled" ? resources.value.items : EMPTY_RESOURCES;
  const resourceTemplatesValue =
    resourceTemplates.status === "fulfilled"
      ? resourceTemplates.value.items
      : EMPTY_RESOURCE_TEMPLATES;
  const promptsValue = prompts.status === "fulfilled" ? prompts.value.items : EMPTY_PROMPTS;

  return {
    errors,
    prompts: promptsValue,
    resourceTemplates: resourceTemplatesValue,
    resources: resourcesValue,
    status: errorCount === 0 ? "ready" : errorCount === 4 ? "error" : "partial",
    tools: toolsValue,
    snapshot: {
      prompts: createCatalogSection(promptsValue, prompts),
      resourceTemplates: createCatalogSection(resourceTemplatesValue, resourceTemplates),
      resources: createCatalogSection(resourcesValue, resources),
      tools: createCatalogSection(toolsValue, tools),
    },
  };
}

type LoadedCatalogSection<Item> = {
  complete: boolean;
  items: Item[];
  nextCursor?: string;
};

async function loadCatalogSection<
  Item,
  Key extends string,
  Result extends { nextCursor?: string } & Record<Key, Item[]>,
>(
  loadPage: (cursor?: string) => Promise<Result>,
  itemKey: Key,
): Promise<LoadedCatalogSection<Item>> {
  const items: Item[] = [];
  let cursor: string | undefined;

  for (let page = 0; page < MAX_CATALOG_PAGES; page += 1) {
    const result = await loadPage(cursor);
    const pageItems = result[itemKey];
    if (Array.isArray(pageItems)) {
      items.push(...(pageItems as Item[]));
    }

    cursor = result.nextCursor;
    if (!cursor) {
      return {
        complete: true,
        items,
      };
    }
  }

  return {
    complete: false,
    items,
    nextCursor: cursor,
  };
}

function createLoadedCatalogSection<Item>(items: Item[]): LoadedCatalogSection<Item> {
  return {
    complete: true,
    items,
  };
}

function createInitializeResult(
  client: Client,
  transport: StreamableHTTPClientTransport,
  input: {
    serverCapabilities: ServerCapabilities | null;
    serverVersion: Implementation | null;
  },
): InitializeResult | null {
  const protocolVersion = transport.protocolVersion;
  if (!protocolVersion || !input.serverCapabilities || !input.serverVersion) {
    return null;
  }

  const instructions = client.getInstructions();

  return {
    capabilities: input.serverCapabilities,
    protocolVersion,
    serverInfo: input.serverVersion,
    ...(instructions ? { instructions } : {}),
  };
}

function createServerProfile(input: {
  auth: McpAuthProfile;
  catalog: Awaited<ReturnType<typeof loadCatalog>>;
  initialize: InitializeResult | null;
  transport: StreamableHTTPClientTransport;
  url: URL;
}): McpServerProfile {
  return {
    auth: input.auth,
    catalog: input.catalog.snapshot,
    fetchedAt: Date.now(),
    initialize: input.initialize,
    transport: {
      endpoint: input.url.toString(),
      kind: "streamable-http",
      ...(input.transport.protocolVersion
        ? { protocolVersion: input.transport.protocolVersion }
        : {}),
      sessionMode: input.transport.sessionId
        ? "stateful"
        : input.initialize
          ? "stateless"
          : "unknown",
    },
    url: input.url.toString(),
  };
}

function createAuthProfile(
  connectionOptions: UseMcpActionOptions,
  oauthProvider: PendingOAuthProvider | undefined,
): McpAuthProfile {
  if (connectionOptions.bearerToken) {
    return { mode: "external-bearer" };
  }

  const discoveryState = oauthProvider?.currentDiscoveryState();
  const protectedResourceMetadataUrl = oauthProvider?.resourceMetadataUrl();
  if (discoveryState?.resourceMetadata || discoveryState?.authorizationServerMetadata) {
    return {
      mode: "oauth-protected",
      ...(protectedResourceMetadataUrl ? { protectedResourceMetadataUrl } : {}),
      ...(discoveryState.resourceMetadata
        ? { protectedResourceMetadata: discoveryState.resourceMetadata }
        : {}),
      authorizationServerUrl: discoveryState.authorizationServerUrl,
      ...(discoveryState.authorizationServerMetadata
        ? { authorizationServerMetadata: discoveryState.authorizationServerMetadata }
        : {}),
    };
  }

  return { mode: "none" };
}

function createCatalogSection<Item>(
  items: Item[],
  result: PromiseSettledResult<LoadedCatalogSection<Item>>,
): McpCatalogSection<Item> {
  if (result.status === "rejected") {
    return {
      complete: false,
      error: result.reason,
      items,
    };
  }

  return {
    complete: result.value.complete,
    items,
    ...(result.value.nextCursor ? { nextCursor: result.value.nextCursor } : {}),
  };
}

async function closeConnection(connection: Connection): Promise<void> {
  try {
    if (connection.transport.sessionId) {
      await connection.transport.terminateSession();
    }
  } finally {
    await connection.client.close();
  }
}

async function yieldToBrowser(delayMs: number): Promise<void> {
  await new Promise<void>((resolve) => {
    window.setTimeout(resolve, delayMs);
  });
}

function createAuthenticationChallengeCapturingFetch(input: {
  oauthProvider: PendingOAuthProvider | undefined;
  onAuthenticateHeader: (header: string | null) => void;
  serverUrl: URL;
  transportProxy: UseMcpTransportProxy | undefined;
}): FetchLike {
  return async (url, init) => {
    const requestedUrl = new URL(url.toString());
    const transportProxyUrl = normalizeTransportProxyUrl(input.transportProxy);
    const shouldProxyTransport =
      transportProxyUrl &&
      isSameUrlWithoutHash(requestedUrl, input.serverUrl) &&
      isMcpTransportMethod(init?.method);
    if (shouldProxyTransport && isMcpTransportSseProbe(init?.method)) {
      return new Response("SSE is not enabled for this stateless transport proxy", {
        status: 405,
        statusText: "Method Not Allowed",
      });
    }
    const response = await fetch(
      shouldProxyTransport ? transportProxyUrl : requestedUrl,
      shouldProxyTransport ? createTransportProxyInit(init, input.serverUrl) : init,
    );
    const requestedUrlString = requestedUrl.toString();

    if (response.ok && isProtectedResourceMetadataUrl(requestedUrlString)) {
      input.oauthProvider?.captureDiscoveredResourceMetadataUrl(requestedUrlString);
    }

    if (response.status === 401) {
      const authenticateHeader = response.headers.get("www-authenticate");
      input.onAuthenticateHeader(authenticateHeader);

      if (parseBearerAuthRequirement(authenticateHeader)) {
        await response.body?.cancel();
        throw new Error("Bearer token required.");
      }
      const sanitizedResponse = removeNonBearerResourceMetadataChallenge(
        response,
        authenticateHeader,
      );
      if (sanitizedResponse) {
        return sanitizedResponse;
      }
    }

    return response;
  };
}

function removeNonBearerResourceMetadataChallenge(
  response: Response,
  authenticateHeader: string | null,
): Response | null {
  if (
    !authenticateHeader ||
    findWwwAuthenticateChallenge(authenticateHeader, "Bearer")?.parameters.get(
      "resource_metadata",
    ) ||
    !readWwwAuthenticateParameter(authenticateHeader, "resource_metadata")
  ) {
    return null;
  }

  const headers = new Headers(response.headers);
  headers.delete("www-authenticate");

  return new Response(response.body, {
    headers,
    status: response.status,
    statusText: response.statusText,
  });
}

function isSameUrlWithoutHash(left: URL, right: URL): boolean {
  const normalizedLeft = new URL(left.toString());
  const normalizedRight = new URL(right.toString());
  normalizedLeft.hash = "";
  normalizedRight.hash = "";

  return normalizedLeft.toString() === normalizedRight.toString();
}

function isMcpTransportMethod(method: string | undefined): boolean {
  const normalizedMethod = (method ?? "GET").toUpperCase();

  return normalizedMethod === "DELETE" || normalizedMethod === "GET" || normalizedMethod === "POST";
}

function isMcpTransportSseProbe(method: string | undefined): boolean {
  return (method ?? "GET").toUpperCase() === "GET";
}

function createTransportProxyInit(init: RequestInit | undefined, serverUrl: URL): RequestInit {
  const headers = new Headers(init?.headers);
  headers.set("x-mcp-target-url", mcpTransportTargetUrl(serverUrl).toString());

  return {
    ...init,
    credentials: "omit",
    headers,
  };
}

function mcpTransportTargetUrl(serverUrl: URL): URL {
  const targetUrl = new URL(serverUrl.toString());
  targetUrl.hash = "";

  return targetUrl;
}

function isProtectedResourceMetadataUrl(url: string): boolean {
  try {
    return new URL(url).pathname.includes("/.well-known/oauth-protected-resource");
  } catch {
    return false;
  }
}

function parseBearerAuthRequirement(header: string | null): McpAuthRequirement | null {
  const bearerChallenge = findWwwAuthenticateChallenge(header, "Bearer");
  if (!bearerChallenge) {
    return null;
  }

  if (bearerChallenge.parameters.get("resource_metadata")) {
    return null;
  }
  if (
    bearerChallenge.parameters.has("error") ||
    bearerChallenge.parameters.has("error_description") ||
    bearerChallenge.parameters.has("error_uri")
  ) {
    return null;
  }

  const scope = bearerChallenge.parameters.get("scope");
  const scopes = scope ? scope.split(/\s+/u).filter(Boolean) : undefined;
  const realm = bearerChallenge.parameters.get("realm");

  return {
    ...(realm ? { realm } : {}),
    reason: "oauth_metadata_absent",
    ...(scopes ? { scopes } : {}),
    type: "bearer",
  };
}

function readWwwAuthenticateParameter(
  header: string,
  parameterName: string,
  scheme?: string,
): string | null {
  for (const challenge of parseWwwAuthenticateChallenges(header)) {
    if (scheme && challenge.scheme.toLowerCase() !== scheme.toLowerCase()) {
      continue;
    }
    const parameter = challenge.parameters.get(parameterName.toLowerCase());
    if (parameter != null) {
      return parameter;
    }
  }

  return null;
}

function findWwwAuthenticateChallenge(
  header: string | null,
  scheme: string,
): { parameters: Map<string, string>; scheme: string } | null {
  if (!header) {
    return null;
  }

  return (
    parseWwwAuthenticateChallenges(header).find(
      (challenge) => challenge.scheme.toLowerCase() === scheme.toLowerCase(),
    ) ?? null
  );
}

function parseWwwAuthenticateChallenges(
  header: string,
): Array<{ parameters: Map<string, string>; scheme: string }> {
  const challenges: Array<{ parameters: Map<string, string>; scheme: string }> = [];
  let index = 0;

  while (index < header.length) {
    index = skipHeaderWhitespaceAndCommas(header, index);
    const scheme = readHeaderToken(header, index);
    if (!scheme.value) {
      break;
    }
    index = scheme.nextIndex;
    const parameters = new Map<string, string>();

    while (index < header.length) {
      index = skipHeaderWhitespace(header, index);
      if (header[index] === ",") {
        const afterComma = skipHeaderWhitespace(header, index + 1);
        const nextToken = readHeaderToken(header, afterComma);
        const afterNextToken = skipHeaderWhitespace(header, nextToken.nextIndex);
        if (nextToken.value && header[afterNextToken] !== "=") {
          index = afterComma;
          break;
        }
        index = afterComma;
      }

      const key = readHeaderToken(header, index);
      index = skipHeaderWhitespace(header, key.nextIndex);
      if (!key.value || header[index] !== "=") {
        break;
      }
      index = skipHeaderWhitespace(header, index + 1);

      const value = readHeaderParameterValue(header, index);
      parameters.set(key.value.toLowerCase(), value.value);
      index = value.nextIndex;
    }

    challenges.push({
      parameters,
      scheme: scheme.value,
    });
  }

  return challenges;
}

function skipHeaderWhitespaceAndCommas(header: string, index: number): number {
  let nextIndex = index;
  while (nextIndex < header.length && /[\s,]/u.test(header[nextIndex]!)) {
    nextIndex += 1;
  }

  return nextIndex;
}

function skipHeaderWhitespace(header: string, index: number): number {
  let nextIndex = index;
  while (nextIndex < header.length && /\s/u.test(header[nextIndex]!)) {
    nextIndex += 1;
  }

  return nextIndex;
}

function readHeaderToken(header: string, index: number): { nextIndex: number; value: string } {
  let nextIndex = index;
  while (nextIndex < header.length && /[!#$%&'*+\-.^_`|~0-9A-Za-z]/u.test(header[nextIndex]!)) {
    nextIndex += 1;
  }

  return {
    nextIndex,
    value: header.slice(index, nextIndex),
  };
}

function readHeaderParameterValue(
  header: string,
  index: number,
): { nextIndex: number; value: string } {
  if (header[index] !== '"') {
    return readHeaderToken(header, index);
  }

  let nextIndex = index + 1;
  let value = "";
  while (nextIndex < header.length) {
    const char = header[nextIndex]!;
    if (char === "\\") {
      const escaped = header[nextIndex + 1];
      if (escaped) {
        value += escaped;
        nextIndex += 2;
        continue;
      }
    }
    if (char === '"') {
      return {
        nextIndex: nextIndex + 1,
        value,
      };
    }
    value += char;
    nextIndex += 1;
  }

  return {
    nextIndex,
    value,
  };
}

type ManualOAuthClientInference = {
  authorizationServerMetadataUrl: string;
  requirement: McpManualOAuthClientRequirement;
  resourceMetadataUrl: string;
};

async function inferManualOAuthClientRequirement(
  serverUrl: URL,
  authenticateHeader: string | null,
): Promise<ManualOAuthClientInference | null> {
  const resourceMetadataUrl = authenticateHeader
    ? readWwwAuthenticateParameter(authenticateHeader, "resource_metadata", "Bearer")
    : null;
  if (!resourceMetadataUrl) {
    return null;
  }

  try {
    const resourceMetadataResponse = await fetch(resourceMetadataUrl);
    if (!resourceMetadataResponse.ok) {
      return null;
    }
    const resourceMetadata = parseProtectedResourceMetadataSubset(
      await resourceMetadataResponse.json(),
    );
    if (!resourceMetadata) {
      return null;
    }
    const resourceUrl = normalizeMcpUrl(resourceMetadata.resource);
    if (!resourceUrl || !isSameUrlWithoutHash(resourceUrl, serverUrl)) {
      return null;
    }
    const authorizationServer = resourceMetadata.authorization_servers?.[0];
    if (!authorizationServer) {
      return null;
    }

    const metadataUrl = authorizationServerMetadataUrlFor(authorizationServer);
    const metadataResponse = await fetch(metadataUrl);
    if (!metadataResponse.ok) {
      return null;
    }
    const metadata = parseAuthorizationServerMetadataSubset(await metadataResponse.json());
    if (!metadata) {
      return null;
    }

    if (metadata.registration_endpoint || metadata.client_id_metadata_document_supported) {
      return null;
    }

    return {
      authorizationServerMetadataUrl: metadataUrl,
      requirement: {
        ...(metadata.authorization_endpoint
          ? { authorizationEndpoint: metadata.authorization_endpoint }
          : {}),
        issuer: metadata.issuer ?? new URL(authorizationServer).toString(),
        reason: "client_registration_unavailable",
        suggestedFields: ["clientId"],
        supportsClientMetadataDocument: false,
        supportsDynamicClientRegistration: false,
        ...(metadata.token_endpoint ? { tokenEndpoint: metadata.token_endpoint } : {}),
        type: "manual_oauth_client",
      },
      resourceMetadataUrl,
    };
  } catch {
    return null;
  }
}

function parseProtectedResourceMetadataSubset(value: unknown): {
  authorization_servers?: string[];
  resource: string;
} | null {
  if (!isRecord(value)) {
    return null;
  }

  const resource = value.resource;
  const authorizationServers = value.authorization_servers;
  if (
    typeof resource !== "string" ||
    (authorizationServers !== undefined && !isStringArray(authorizationServers))
  ) {
    return null;
  }

  return {
    ...(authorizationServers ? { authorization_servers: authorizationServers } : {}),
    resource,
  };
}

function parseAuthorizationServerMetadataSubset(value: unknown): {
  authorization_endpoint?: string;
  client_id_metadata_document_supported?: boolean;
  issuer?: string;
  registration_endpoint?: string;
  token_endpoint?: string;
} | null {
  if (!isRecord(value)) {
    return null;
  }

  const issuer = value.issuer;
  const authorizationEndpoint = value.authorization_endpoint;
  const tokenEndpoint = value.token_endpoint;
  const registrationEndpoint = value.registration_endpoint;
  const supportsClientMetadataDocument = value.client_id_metadata_document_supported;
  if (
    (issuer !== undefined && typeof issuer !== "string") ||
    (authorizationEndpoint !== undefined && typeof authorizationEndpoint !== "string") ||
    (tokenEndpoint !== undefined && typeof tokenEndpoint !== "string") ||
    (registrationEndpoint !== undefined && typeof registrationEndpoint !== "string") ||
    (supportsClientMetadataDocument !== undefined &&
      typeof supportsClientMetadataDocument !== "boolean")
  ) {
    return null;
  }

  return {
    ...(authorizationEndpoint ? { authorization_endpoint: authorizationEndpoint } : {}),
    ...(supportsClientMetadataDocument !== undefined
      ? { client_id_metadata_document_supported: supportsClientMetadataDocument }
      : {}),
    ...(issuer ? { issuer } : {}),
    ...(registrationEndpoint ? { registration_endpoint: registrationEndpoint } : {}),
    ...(tokenEndpoint ? { token_endpoint: tokenEndpoint } : {}),
  };
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function isStringArray(value: unknown): value is string[] {
  return Array.isArray(value) && value.every((item) => typeof item === "string");
}

const customStorageIds = new WeakMap<McpStorage, number>();
let nextCustomStorageId = 1;

function getMcpStorageDependencyKey(storage: McpStorage | false | undefined): string {
  if (storage === false) {
    return "memory";
  }
  if (!storage) {
    return "default";
  }

  const existingId = customStorageIds.get(storage);
  if (existingId) {
    return `custom:${existingId}`;
  }

  const id = nextCustomStorageId;
  nextCustomStorageId += 1;
  customStorageIds.set(storage, id);

  return `custom:${id}`;
}

function createOAuthProviderKey(url: URL, options: UseMcpActionOptions): string {
  return stableSerializeJsonValue({
    clientId: options.oauth?.clientId,
    clientMetadata: options.oauth?.clientMetadata,
    clientMetadataUrl: options.oauth?.clientMetadataUrl,
    redirectUrl: resolveOAuthRedirectUrl(options.oauth?.redirectUrl),
    storage: getMcpStorageDependencyKey(options.storage),
    url: url.toString(),
  });
}

function resolveMcpStorage(storage: McpStorage | false | undefined): McpStorage | null {
  if (storage === false) {
    return null;
  }
  if (storage) {
    return storage;
  }
  if (typeof window === "undefined" || !window.localStorage) {
    return null;
  }

  return {
    async getItem(key) {
      return window.localStorage.getItem(key);
    },
    async removeItem(key) {
      window.localStorage.removeItem(key);
    },
    async setItem(key, value) {
      window.localStorage.setItem(key, value);
    },
  };
}

type OAuthStorageKeys = {
  client: string;
  discovery: string;
  state: string;
  tokens: string;
  verifier: string;
};

function createOAuthStorageKeys(
  serverUrl: URL,
  input: {
    clientId?: string;
    clientMetadata: OAuthClientMetadata;
    clientMetadataUrl?: string;
    redirectUrl: string;
  },
): OAuthStorageKeys {
  const serverHash = sha256Hex(
    stableSerializeJsonValue({
      clientId: input.clientId,
      clientMetadata: input.clientMetadata,
      clientMetadataUrl: input.clientMetadataUrl,
      redirectUrl: input.redirectUrl,
      serverUrl: canonicalizeOAuthStorageServerUrl(serverUrl),
    }),
  );
  const prefix = `use-mcp-react:v1:${serverHash}`;

  return {
    client: `${prefix}:client`,
    discovery: `${prefix}:discovery`,
    state: `${prefix}:state`,
    tokens: `${prefix}:tokens`,
    verifier: `${prefix}:verifier`,
  };
}

function canonicalizeOAuthStorageServerUrl(serverUrl: URL): string {
  const url = new URL(serverUrl.toString());
  url.hash = "";
  url.hostname = url.hostname.toLowerCase();
  url.protocol = url.protocol.toLowerCase();

  return url.toString();
}

const SHA256_K = [
  0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
  0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
  0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
  0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
  0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
  0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
  0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
  0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
];

function sha256Hex(value: string): string {
  const bytes = new TextEncoder().encode(value);
  const bitLength = bytes.length * 8;
  const paddedLength = Math.ceil((bytes.length + 9) / 64) * 64;
  const padded = new Uint8Array(paddedLength);
  padded.set(bytes);
  padded[bytes.length] = 0x80;

  const view = new DataView(padded.buffer);
  view.setUint32(paddedLength - 8, Math.floor(bitLength / 0x100000000));
  view.setUint32(paddedLength - 4, bitLength >>> 0);

  let h0 = 0x6a09e667;
  let h1 = 0xbb67ae85;
  let h2 = 0x3c6ef372;
  let h3 = 0xa54ff53a;
  let h4 = 0x510e527f;
  let h5 = 0x9b05688c;
  let h6 = 0x1f83d9ab;
  let h7 = 0x5be0cd19;
  const words = new Uint32Array(64);

  for (let offset = 0; offset < paddedLength; offset += 64) {
    for (let index = 0; index < 16; index += 1) {
      words[index] = view.getUint32(offset + index * 4);
    }

    for (let index = 16; index < 64; index += 1) {
      const s0 =
        rotateRight(words[index - 15]!, 7) ^
        rotateRight(words[index - 15]!, 18) ^
        (words[index - 15]! >>> 3);
      const s1 =
        rotateRight(words[index - 2]!, 17) ^
        rotateRight(words[index - 2]!, 19) ^
        (words[index - 2]! >>> 10);
      words[index] = (words[index - 16]! + s0 + words[index - 7]! + s1) >>> 0;
    }

    let a = h0;
    let b = h1;
    let c = h2;
    let d = h3;
    let e = h4;
    let f = h5;
    let g = h6;
    let h = h7;

    for (let index = 0; index < 64; index += 1) {
      const s1 = rotateRight(e, 6) ^ rotateRight(e, 11) ^ rotateRight(e, 25);
      const choice = (e & f) ^ (~e & g);
      const temp1 = (h + s1 + choice + SHA256_K[index]! + words[index]!) >>> 0;
      const s0 = rotateRight(a, 2) ^ rotateRight(a, 13) ^ rotateRight(a, 22);
      const majority = (a & b) ^ (a & c) ^ (b & c);
      const temp2 = (s0 + majority) >>> 0;

      h = g;
      g = f;
      f = e;
      e = (d + temp1) >>> 0;
      d = c;
      c = b;
      b = a;
      a = (temp1 + temp2) >>> 0;
    }

    h0 = (h0 + a) >>> 0;
    h1 = (h1 + b) >>> 0;
    h2 = (h2 + c) >>> 0;
    h3 = (h3 + d) >>> 0;
    h4 = (h4 + e) >>> 0;
    h5 = (h5 + f) >>> 0;
    h6 = (h6 + g) >>> 0;
    h7 = (h7 + h) >>> 0;
  }

  return [h0, h1, h2, h3, h4, h5, h6, h7]
    .map((word) => word.toString(16).padStart(8, "0"))
    .join("");
}

function rotateRight(value: number, bits: number): number {
  return (value >>> bits) | (value << (32 - bits));
}

async function readStorageJson<T>(
  storage: McpStorage | null,
  key: string,
  parse: (value: unknown) => T | undefined,
): Promise<T | undefined> {
  if (!storage) {
    return undefined;
  }

  const storedValue = await storage.getItem(key);
  if (!storedValue) {
    return undefined;
  }

  try {
    return parse(JSON.parse(storedValue));
  } catch {
    await storage.removeItem(key);
    return undefined;
  }
}

async function writeStorageJson(
  storage: McpStorage | null,
  key: string,
  value: unknown,
): Promise<void> {
  if (!storage) {
    return;
  }

  await storage.setItem(key, JSON.stringify(value));
}

function parseStoredClientInformation(value: unknown): OAuthClientInformationMixed | undefined {
  if (!isRecord(value) || typeof value.client_id !== "string") {
    return undefined;
  }

  return value as OAuthClientInformationMixed;
}

function parseStoredTokens(value: unknown): OAuthTokens | undefined {
  if (
    !isRecord(value) ||
    typeof value.access_token !== "string" ||
    typeof value.token_type !== "string"
  ) {
    return undefined;
  }

  return value as OAuthTokens;
}

function parseStoredDiscoveryState(value: unknown): OAuthDiscoveryState | undefined {
  if (!isRecord(value) || typeof value.authorizationServerUrl !== "string") {
    return undefined;
  }

  return value as unknown as OAuthDiscoveryState;
}

function parseStoredString(value: unknown): string | undefined {
  return typeof value === "string" ? value : undefined;
}

function isMcpOAuthCallbackMessage(value: unknown): value is McpOAuthCallbackMessage {
  return (
    isRecord(value) &&
    value.type === "use-mcp-react:oauth-callback" &&
    (value.code === undefined || typeof value.code === "string") &&
    (value.error === undefined || typeof value.error === "string") &&
    (value.errorDescription === undefined || typeof value.errorDescription === "string") &&
    (value.state === undefined || typeof value.state === "string")
  );
}

function createStaticBearerAuthProvider(bearerToken: string): OAuthClientProvider {
  return new StaticBearerAuthProvider(bearerToken);
}

class PendingOAuthProvider implements OAuthClientProvider {
  readonly clientMetadata: OAuthClientMetadata;
  readonly clientMetadataUrl?: string;
  readonly redirectUrl: string;

  private authorizationUrl: URL | null = null;
  private client: OAuthClientInformationMixed | undefined;
  private discoveredResourceMetadataUrl: string | undefined;
  private oauthState: string | undefined;
  private parsedResourceMetadataUrlFromChallenge: string | undefined;
  private savedTokens: OAuthTokens | undefined;
  private savedDiscoveryState: OAuthDiscoveryState | undefined;
  private readonly storage: McpStorage | null;
  private readonly storageKeys: OAuthStorageKeys;
  private target: AuthorizationTarget | null = null;
  private verifier: string | undefined;
  private usedClientMetadataDocument = false;
  private usedDynamicClientRegistration = false;

  constructor(
    serverUrl: URL,
    oauthOptions: UseMcpOAuthOptions = {},
    storage: McpStorage | null = null,
  ) {
    this.redirectUrl = resolveOAuthRedirectUrl(oauthOptions.redirectUrl);
    this.clientMetadataUrl = oauthOptions.clientMetadataUrl;
    this.storage = storage;
    this.clientMetadata = {
      client_name: "use-mcp-react browser client",
      grant_types: ["authorization_code", "refresh_token"],
      redirect_uris: [this.redirectUrl],
      response_types: ["code"],
      token_endpoint_auth_method: "none",
      ...oauthOptions.clientMetadata,
    };
    this.client = oauthOptions.clientId
      ? {
          client_id: oauthOptions.clientId,
        }
      : undefined;
    this.storageKeys = createOAuthStorageKeys(serverUrl, {
      clientId: oauthOptions.clientId,
      clientMetadata: this.clientMetadata,
      clientMetadataUrl: this.clientMetadataUrl,
      redirectUrl: this.redirectUrl,
    });
  }

  authRequirement(): Extract<McpAuthRequirement, { type: "oauth" }> | null {
    if (!this.authorizationUrl) {
      return null;
    }

    const scope = this.authorizationUrl.searchParams.get("scope");
    const scopes = scope ? scope.split(/\s+/u).filter(Boolean) : undefined;
    const issuer = this.authorizationServerIssuer();

    return {
      authorizationUrl: this.authorizationUrl,
      ...(issuer ? { issuer } : {}),
      ...(scopes ? { scopes } : {}),
      supportsClientMetadataDocument:
        this.savedDiscoveryState?.authorizationServerMetadata
          ?.client_id_metadata_document_supported === true,
      supportsDynamicClientRegistration: Boolean(
        this.savedDiscoveryState?.authorizationServerMetadata?.registration_endpoint,
      ),
      type: "oauth",
    };
  }

  authDiagnostics(): McpAuthDiagnostics | null {
    const requirement = this.authRequirement();
    if (!requirement) {
      return null;
    }

    return {
      issuer: requirement.issuer,
      authorizationServerMetadataUrl: this.savedDiscoveryState?.authorizationServerUrl
        ? authorizationServerMetadataUrlFor(this.savedDiscoveryState.authorizationServerUrl)
        : undefined,
      resourceMetadataUrl: this.resourceMetadataUrl(),
      registrationStrategy: this.usedClientMetadataDocument
        ? "client_metadata_url"
        : this.usedDynamicClientRegistration
          ? "dynamic_client_registration"
          : this.client
            ? "client_id"
            : undefined,
      scopes: requirement.scopes,
    };
  }

  captureAuthenticationChallenge(header: string | null): void {
    this.parsedResourceMetadataUrlFromChallenge = header
      ? (readWwwAuthenticateParameter(header, "resource_metadata", "Bearer") ?? undefined)
      : undefined;
  }

  captureDiscoveredResourceMetadataUrl(resourceMetadataUrl: string): void {
    this.discoveredResourceMetadataUrl = resourceMetadataUrl;
  }

  clearAuthenticationChallenge(): void {
    this.discoveredResourceMetadataUrl = undefined;
    this.parsedResourceMetadataUrlFromChallenge = undefined;
  }

  resourceMetadataUrl(): string | undefined {
    // Work around SDK 1.29.0 losing the PRM URL on GET 401 and internal discovery.
    // See docs/reference/sdk-resource-metadata-url-loss.md.
    return (
      this.savedDiscoveryState?.resourceMetadataUrl ??
      this.discoveredResourceMetadataUrl ??
      this.parsedResourceMetadataUrlFromChallenge
    );
  }

  async clientInformation(): Promise<OAuthClientInformationMixed | undefined> {
    if (this.client) {
      return this.client;
    }

    this.client = await readStorageJson(
      this.storage,
      this.storageKeys.client,
      parseStoredClientInformation,
    );
    if (this.client) {
      this.rememberRegistrationStrategy(this.client);
    }
    return this.client;
  }

  async saveClientInformation(clientInformation: OAuthClientInformationMixed): Promise<void> {
    this.client = clientInformation;
    this.rememberRegistrationStrategy(clientInformation);
    await writeStorageJson(this.storage, this.storageKeys.client, clientInformation);
  }

  async tokens(): Promise<OAuthTokens | undefined> {
    if (this.savedTokens) {
      return this.savedTokens;
    }

    this.savedTokens = await readStorageJson(
      this.storage,
      this.storageKeys.tokens,
      parseStoredTokens,
    );
    return this.savedTokens;
  }

  async state(): Promise<string> {
    this.oauthState = crypto.randomUUID();
    await writeStorageJson(this.storage, this.storageKeys.state, this.oauthState);

    return this.oauthState;
  }

  async saveTokens(tokens: OAuthTokens): Promise<void> {
    this.savedTokens = tokens;
    await writeStorageJson(this.storage, this.storageKeys.tokens, tokens);
  }

  async discoveryState(): Promise<OAuthDiscoveryState | undefined> {
    if (this.savedDiscoveryState) {
      return this.savedDiscoveryState;
    }

    this.savedDiscoveryState = await readStorageJson(
      this.storage,
      this.storageKeys.discovery,
      parseStoredDiscoveryState,
    );
    return this.savedDiscoveryState;
  }

  currentDiscoveryState(): OAuthDiscoveryState | undefined {
    return this.savedDiscoveryState;
  }

  async saveDiscoveryState(state: OAuthDiscoveryState): Promise<void> {
    this.savedDiscoveryState = state;
    await writeStorageJson(this.storage, this.storageKeys.discovery, state);
  }

  async invalidateCredentials(
    scope: "all" | "client" | "tokens" | "verifier" | "discovery",
  ): Promise<void> {
    if (scope === "all" || scope === "client") {
      this.client = undefined;
      this.usedClientMetadataDocument = false;
      this.usedDynamicClientRegistration = false;
      await this.storage?.removeItem(this.storageKeys.client);
    }
    if (scope === "all" || scope === "tokens") {
      this.savedTokens = undefined;
      await this.storage?.removeItem(this.storageKeys.tokens);
    }
    if (scope === "all" || scope === "verifier") {
      this.verifier = undefined;
      this.oauthState = undefined;
      await this.storage?.removeItem(this.storageKeys.verifier);
      await this.storage?.removeItem(this.storageKeys.state);
    }
    if (scope === "all" || scope === "discovery") {
      this.savedDiscoveryState = undefined;
      await this.storage?.removeItem(this.storageKeys.discovery);
    }
  }

  redirectToAuthorization(authorizationUrl: URL): void {
    this.authorizationUrl = new URL(authorizationUrl.toString());
    if (this.target && !this.target.closed) {
      this.target.location.href = this.authorizationUrl.toString();
      this.target.focus();
    }
    this.target = null;
  }

  async saveCodeVerifier(codeVerifier: string): Promise<void> {
    this.verifier = codeVerifier;
    await writeStorageJson(this.storage, this.storageKeys.verifier, codeVerifier);
  }

  async codeVerifier(): Promise<string> {
    const verifier =
      this.verifier ??
      (await readStorageJson(this.storage, this.storageKeys.verifier, parseStoredString));
    if (!verifier) {
      throw new Error("No OAuth PKCE verifier saved.");
    }

    this.verifier = verifier;
    return verifier;
  }

  pendingState(): string | null {
    return this.oauthState ?? this.authorizationUrl?.searchParams.get("state") ?? null;
  }

  setAuthorizationTarget(target: AuthorizationTarget): void {
    this.target = target;
  }

  private rememberRegistrationStrategy(clientInformation: OAuthClientInformationMixed): void {
    this.usedClientMetadataDocument =
      Boolean(this.clientMetadataUrl) && clientInformation.client_id === this.clientMetadataUrl;
    this.usedDynamicClientRegistration = !this.usedClientMetadataDocument;
  }

  private authorizationServerIssuer(): string | undefined {
    return (
      this.savedDiscoveryState?.authorizationServerMetadata?.issuer ??
      this.savedDiscoveryState?.authorizationServerUrl ??
      this.authorizationUrl?.origin
    );
  }
}

function prepareAuthorizationTarget(
  provider: PendingOAuthProvider | undefined,
  authorizationTarget: UseMcpActionOptions["authorizationTarget"],
  popupWindowName: () => string,
): PreparedAuthorizationTargetResult {
  if (!provider || !authorizationTarget) {
    return { ok: true };
  }

  if (authorizationTarget === "popup") {
    const popup = window.open(
      "about:blank",
      popupWindowName(),
      "width=600,height=700,resizable=yes,scrollbars=yes,status=yes",
    );
    if (!popup) {
      return { ok: false, reason: "popup_blocked" };
    }
    provider.setAuthorizationTarget(popup);
    popup.focus();
    return { ok: true, ownsTarget: true, target: popup };
  }

  provider.setAuthorizationTarget(authorizationTarget);
  authorizationTarget.focus();
  return { ok: true, ownsTarget: false, target: authorizationTarget };
}

function createOAuthPopupWindowName(): string {
  return `use-mcp-react-oauth-${crypto.randomUUID()}`;
}

function resolveOAuthRedirectUrl(redirectUrl: URL | string | undefined): string {
  const origin = typeof window === "undefined" ? "http://localhost" : window.location.origin;
  if (!redirectUrl) {
    return `${origin}/oauth/callback`;
  }

  return new URL(redirectUrl, origin).toString();
}

class StaticBearerAuthProvider implements OAuthClientProvider {
  readonly clientMetadata: OAuthClientMetadata = {
    client_name: "use-mcp-react static bearer client",
    grant_types: [],
    redirect_uris: [],
    response_types: [],
    token_endpoint_auth_method: "none",
  };

  readonly redirectUrl = undefined;

  constructor(private readonly bearerToken: string) {}

  clientInformation(): OAuthClientInformationMixed {
    return {
      client_id: "use-mcp-react-static-bearer",
      grant_types: [],
      redirect_uris: [],
      response_types: [],
      token_endpoint_auth_method: "none",
    };
  }

  async tokens(): Promise<OAuthTokens> {
    return {
      access_token: await this.readToken(),
      token_type: "Bearer",
    };
  }

  saveTokens(): void {
    throw new Error("Static bearer auth does not save OAuth tokens.");
  }

  redirectToAuthorization(): void {
    throw new Error("Static bearer auth does not redirect.");
  }

  saveCodeVerifier(): void {
    throw new Error("Static bearer auth does not use PKCE.");
  }

  codeVerifier(): string {
    throw new Error("Static bearer auth does not use PKCE.");
  }

  private async readToken(): Promise<string> {
    return this.bearerToken;
  }
}
